baseURL = "https://yellowfang.github.io/"
title = "Blog"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-hello-programmer-theme"

paginate = 7

[author]
		name = "yellowfang"
		email = "shie44167@gmail.com"
